### ISSUE TITLE
질문 있습니다!

### ISSUE THREAD

**Issue by seuli23** [yamoo9/fastcampus-front-end-design#1]
지금 복습 중인데, ! 치고 tab 해도 아무 반응이 없네요ㅠ
해당 프로그램은 다 설치된 상태입니다.
이유가 뭘까요..

그리고, 저장소를 하나 더 만들어서 복습하고 싶은데, 수업 때 만든 저장소를 삭제하지 않고는 또 만들 수 없나요?
'제이름.github.io'로만 저장소 사용이 가능하다고 하니..

**Comment by yamoo9** [comment]
에디터의 오른쪽 하단 문법 모드가 `HTML`인지 살펴보세요.
`HTML` 문법 모드에서만 `!`를 입력한 후, `Tab` 키를 눌러야 코드가 생성됩니다. 
아래 이미지처럼 `Plain Text`일 경우는 작동되지 않아요.

[![1.png](https://s10.postimg.org/xvc46fkop/image.png)](https://postimg.org/image/6xi74p01h/)

<br>

그리고 `github.io` 페이지는 GitHub에서 호스팅을 해주는 무료 서비스라 [GitHub Pages documentation에서 요구하는데로만 사용이 가능](https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages)합니다.

아래 이미지를 살펴보시면 요구 사항이 __오직 자신의 계정 이름으로만 github.io 페이지 서비스가 가능__ 하다고 명시 되어 있습니다. 복습 하고자 한다면 기존의 내용을 하위 폴더에 모두 넣은 후, 테스트 해보시면 좋겠네요. 😃 

> You can only use your own account name for a User or Organization Page repository. A repository like joe/bob.github.io will not build a User Pages site.



![image](https://cloud.githubusercontent.com/assets/1850554/19136360/ff579d32-8ba6-11e6-918e-010b0ce0a050.png)
